-- Migration: RefinarEstruturaBancoInstitucional
-- Projeto: Sistema de Ponto Acadêmico
-- Objetivo: melhorar integridade, índices, auditoria e organização do PostgreSQL
-- sem apagar dados e sem renomear as tabelas usadas pela API.

BEGIN;

CREATE TABLE IF NOT EXISTS app_orgaos (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(160) NOT NULL UNIQUE,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NULL,
    criado_por integer NULL,
    atualizado_por integer NULL
);

ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT;
ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_usuarios ALTER COLUMN nome_completo TYPE varchar(180);
ALTER TABLE app_usuarios ALTER COLUMN cpf TYPE varchar(14);
ALTER TABLE app_usuarios ALTER COLUMN email TYPE varchar(180);
ALTER TABLE app_usuarios ALTER COLUMN tipo_usuario TYPE varchar(20);
ALTER TABLE app_usuarios ALTER COLUMN orgao TYPE varchar(160);

ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS horario_inicio time without time zone NULL;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS horario_fim time without time zone NULL;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone NOT NULL DEFAULT now();
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone NULL;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS estado_civil text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS profissao text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS escolaridade text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS tipo_ensino text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS instituicao_ensino text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS curso text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS periodo_semestre text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS telefone_celular text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS telefone_residencial text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS cep text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS logradouro text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS numero text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS complemento text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS bairro text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS cidade text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT '';
ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS situacao_academico text NOT NULL DEFAULT 'Acadêmico ativo';

CREATE TABLE IF NOT EXISTS app_supervisores (
    usuario_id integer PRIMARY KEY REFERENCES app_usuarios(id) ON DELETE CASCADE,
    orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT,
    ativo boolean NOT NULL DEFAULT true,
    criado_em timestamp without time zone NOT NULL DEFAULT now(),
    atualizado_em timestamp without time zone NULL,
    criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
    atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL
);

ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone NOT NULL DEFAULT now();
ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

INSERT INTO app_orgaos (nome)
SELECT DISTINCT NULLIF(TRIM(orgao), '')
FROM app_usuarios
WHERE NULLIF(TRIM(orgao), '') IS NOT NULL
ON CONFLICT (nome) DO NOTHING;

UPDATE app_usuarios u
SET orgao_id = o.id
FROM app_orgaos o
WHERE u.orgao_id IS NULL
  AND o.nome = u.orgao;

UPDATE app_academicos a
SET orgao_id = u.orgao_id
FROM app_usuarios u
WHERE a.usuario_id = u.id
  AND a.orgao_id IS NULL;

INSERT INTO app_supervisores (usuario_id, orgao_id)
SELECT id, orgao_id
FROM app_usuarios
WHERE tipo_usuario = 'SUPERVISOR'
ON CONFLICT (usuario_id) DO UPDATE SET orgao_id = EXCLUDED.orgao_id;

DO $$
BEGIN
    ALTER TABLE app_usuarios ADD CONSTRAINT ck_app_usuarios_tipo
        CHECK (tipo_usuario IN ('ACADEMICO', 'SUPERVISOR')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_usuarios ADD CONSTRAINT ck_app_usuarios_cpf
        CHECK (length(regexp_replace(cpf, '\D', '', 'g')) = 11) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_academicos ADD CONSTRAINT ck_app_academicos_tipo_ensino
        CHECK (tipo_ensino IN ('', 'Médio', 'Superior')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_academicos ADD CONSTRAINT ck_app_academicos_situacao
        CHECK (situacao_academico IN ('Acadêmico ativo', 'Acadêmico desativado')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_pontos ADD CONSTRAINT ck_app_pontos_status
        CHECK (status IN ('PENDENTE', 'PRESENTE', 'AUSENTE', 'FALTA_JUSTIFICADA', 'FALTA_NAO_JUSTIFICADA', 'PRESENCA_REGULARIZADA')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_historicos ADD CONSTRAINT ck_app_historicos_tipo_dia
        CHECK (tipo_dia IN ('UTIL', 'SABADO', 'DOMINGO', 'FERIADO')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE app_ausencias DROP CONSTRAINT IF EXISTS ck_app_ausencias_tipo;
    ALTER TABLE app_ausencias ADD CONSTRAINT ck_app_ausencias_tipo
        CHECK (tipo IN ('AUSENTE', 'JUSTIFICADA', 'NAO_JUSTIFICADA', 'REGULARIZADA')) NOT VALID;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_app_usuarios_email_lower'
    ) THEN
        IF NOT EXISTS (
            SELECT lower(email)
            FROM app_usuarios
            GROUP BY lower(email)
            HAVING count(*) > 1
        ) THEN
            CREATE UNIQUE INDEX ux_app_usuarios_email_lower ON app_usuarios (lower(email));
        ELSE
            CREATE INDEX IF NOT EXISTS ix_app_usuarios_email_lower ON app_usuarios (lower(email));
        END IF;
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS ix_app_usuarios_tipo_usuario ON app_usuarios (tipo_usuario);
CREATE INDEX IF NOT EXISTS ix_app_usuarios_orgao_id ON app_usuarios (orgao_id);
CREATE INDEX IF NOT EXISTS ix_app_academicos_orgao_id ON app_academicos (orgao_id);
CREATE INDEX IF NOT EXISTS ix_app_academicos_supervisor_id ON app_academicos (supervisor_id);
CREATE INDEX IF NOT EXISTS ix_app_pontos_academico_data ON app_pontos (academico_id, data);
CREATE INDEX IF NOT EXISTS ix_app_pontos_status ON app_pontos (status);
CREATE INDEX IF NOT EXISTS ix_app_historicos_mes ON app_historicos (academico_id, ano, mes);
CREATE INDEX IF NOT EXISTS ix_app_historicos_tipo_dia ON app_historicos (tipo_dia);
CREATE INDEX IF NOT EXISTS ix_app_ausencias_academico_data ON app_ausencias (academico_id, data);
CREATE INDEX IF NOT EXISTS ix_app_ausencias_supervisor_id ON app_ausencias (supervisor_id);

CREATE OR REPLACE VIEW usuarios AS
SELECT id, nome_completo, cpf, data_nascimento, email, tipo_usuario, orgao, orgao_id,
       ativo, criado_em, atualizado_em, criado_por, atualizado_por
FROM app_usuarios;

CREATE OR REPLACE VIEW academicos AS
SELECT a.*, u.nome_completo, u.cpf, u.data_nascimento, u.email, u.orgao
FROM app_academicos a
JOIN app_usuarios u ON u.id = a.usuario_id;

CREATE OR REPLACE VIEW supervisores AS
SELECT s.*, u.nome_completo, u.cpf, u.email, u.orgao
FROM app_supervisores s
JOIN app_usuarios u ON u.id = s.usuario_id;

CREATE OR REPLACE VIEW pontos AS
SELECT * FROM app_pontos;

CREATE OR REPLACE VIEW historico_mensal AS
SELECT * FROM app_historicos;

CREATE OR REPLACE VIEW ausencias AS
SELECT * FROM app_ausencias;

CREATE OR REPLACE VIEW orgaos AS
SELECT * FROM app_orgaos;

CREATE OR REPLACE VIEW observacoes_supervisor AS
SELECT id, academico_id, make_date(ano, mes, dia) AS data, observacao_supervisor,
       atualizado_por_supervisor_id, atualizado_em
FROM app_historicos
WHERE observacao_supervisor <> '';

COMMIT;
