using Npgsql;
using PontoApi.Models;
using PontoApi.Services;

namespace PontoApi.Data;

public static class Banco
{
    public static async Task<NpgsqlConnection> Abrir(string connectionString)
    {
        var con = new NpgsqlConnection(connectionString);
        await con.OpenAsync();
        return con;
    }

    public static async Task CriarEstrutura(string connectionString)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            CREATE TABLE IF NOT EXISTS app_orgaos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome varchar(160) NOT NULL UNIQUE,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL,
                atualizado_por integer NULL
            );

            CREATE TABLE IF NOT EXISTS app_usuarios (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nome_completo varchar(180) NOT NULL,
                cpf varchar(14) NOT NULL UNIQUE,
                data_nascimento timestamp without time zone NULL,
                email varchar(180) NOT NULL,
                senha_hash text NOT NULL,
                tipo_usuario varchar(20) NOT NULL,
                orgao varchar(160) NOT NULL,
                orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL
            );

            ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT;
            ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
            ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_usuarios ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_usuarios ALTER COLUMN nome_completo TYPE varchar(180);
            ALTER TABLE app_usuarios ALTER COLUMN cpf TYPE varchar(14);
            ALTER TABLE app_usuarios ALTER COLUMN email TYPE varchar(180);
            ALTER TABLE app_usuarios ALTER COLUMN tipo_usuario TYPE varchar(20);
            ALTER TABLE app_usuarios ALTER COLUMN orgao TYPE varchar(160);

            CREATE TABLE IF NOT EXISTS app_academicos (
                usuario_id integer PRIMARY KEY REFERENCES app_usuarios(id) ON DELETE CASCADE,
                ensino text NOT NULL DEFAULT '',
                endereco text NOT NULL DEFAULT '',
                sexo text NOT NULL DEFAULT '',
                estado_civil text NOT NULL DEFAULT '',
                profissao text NOT NULL DEFAULT '',
                escolaridade text NOT NULL DEFAULT '',
                tipo_ensino text NOT NULL DEFAULT '',
                instituicao_ensino text NOT NULL DEFAULT '',
                curso text NOT NULL DEFAULT '',
                periodo_semestre text NOT NULL DEFAULT '',
                telefone_celular text NOT NULL DEFAULT '',
                telefone_residencial text NOT NULL DEFAULT '',
                cep text NOT NULL DEFAULT '',
                logradouro text NOT NULL DEFAULT '',
                numero text NOT NULL DEFAULT '',
                complemento text NOT NULL DEFAULT '',
                bairro text NOT NULL DEFAULT '',
                cidade text NOT NULL DEFAULT '',
                estado text NOT NULL DEFAULT '',
                dados_contratacao text NOT NULL DEFAULT '',
                setor_alocacao text NOT NULL DEFAULT '',
                orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT,
                horario text NOT NULL DEFAULT '',
                horario_inicio time without time zone NULL,
                horario_fim time without time zone NULL,
                carga_horaria_semanal integer NOT NULL DEFAULT 30,
                situacao_academico text NOT NULL DEFAULT 'Acadêmico ativo',
                supervisor_id integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL
            );

            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS estado_civil text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS profissao text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS escolaridade text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS tipo_ensino text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS instituicao_ensino text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS curso text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS periodo_semestre text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS telefone_celular text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS telefone_residencial text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS cep text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS logradouro text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS numero text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS complemento text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS bairro text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS cidade text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS estado text NOT NULL DEFAULT '';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS situacao_academico text NOT NULL DEFAULT 'Acadêmico ativo';
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS horario_inicio time without time zone NULL;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS horario_fim time without time zone NULL;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone NOT NULL DEFAULT now();
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS atualizado_em timestamp without time zone NULL;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_academicos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

            CREATE TABLE IF NOT EXISTS app_supervisores (
                usuario_id integer PRIMARY KEY REFERENCES app_usuarios(id) ON DELETE CASCADE,
                orgao_id integer NULL REFERENCES app_orgaos(id) ON DELETE RESTRICT,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL
            );

            CREATE TABLE IF NOT EXISTS app_pontos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academico_id integer NOT NULL REFERENCES app_academicos(usuario_id) ON DELETE CASCADE,
                data date NOT NULL,
                entrada timestamp without time zone NULL,
                saida timestamp without time zone NULL,
                horas_cumpridas double precision NOT NULL DEFAULT 0,
                status text NOT NULL DEFAULT 'PENDENTE',
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                UNIQUE (academico_id, data)
            );
            ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
            ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_pontos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

            CREATE TABLE IF NOT EXISTS app_historicos (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academico_id integer NOT NULL REFERENCES app_academicos(usuario_id) ON DELETE CASCADE,
                ano integer NOT NULL,
                mes integer NOT NULL,
                dia integer NOT NULL,
                entrada timestamp without time zone NULL,
                saida timestamp without time zone NULL,
                observacao_supervisor text NOT NULL DEFAULT '',
                tipo_dia text NOT NULL DEFAULT 'UTIL',
                descricao_feriado text NOT NULL DEFAULT '',
                atualizado_por_supervisor_id integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                UNIQUE (academico_id, ano, mes, dia)
            );
            ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
            ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS criado_em timestamp without time zone NOT NULL DEFAULT now();
            ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_historicos ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

            CREATE TABLE IF NOT EXISTS app_ausencias (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                academico_id integer NOT NULL REFERENCES app_academicos(usuario_id) ON DELETE CASCADE,
                data date NOT NULL,
                tipo text NOT NULL,
                observacao text NOT NULL DEFAULT '',
                supervisor_id integer NOT NULL REFERENCES app_usuarios(id) ON DELETE RESTRICT,
                ativo boolean NOT NULL DEFAULT true,
                criado_em timestamp without time zone NOT NULL DEFAULT now(),
                atualizado_em timestamp without time zone NULL,
                criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL,
                atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL
            );
            ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS ativo boolean NOT NULL DEFAULT true;
            ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS criado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;
            ALTER TABLE app_ausencias ADD COLUMN IF NOT EXISTS atualizado_por integer NULL REFERENCES app_usuarios(id) ON DELETE SET NULL;

            INSERT INTO app_orgaos (nome)
            SELECT DISTINCT NULLIF(TRIM(orgao), '')
            FROM app_usuarios
            WHERE NULLIF(TRIM(orgao), '') IS NOT NULL
            ON CONFLICT (nome) DO NOTHING;

            UPDATE app_usuarios u
            SET orgao_id = o.id
            FROM app_orgaos o
            WHERE u.orgao_id IS NULL AND o.nome = u.orgao;

            UPDATE app_academicos a
            SET orgao_id = u.orgao_id
            FROM app_usuarios u
            WHERE a.usuario_id = u.id AND a.orgao_id IS NULL;

            INSERT INTO app_supervisores (usuario_id, orgao_id)
            SELECT id, orgao_id
            FROM app_usuarios
            WHERE tipo_usuario = 'SUPERVISOR'
            ON CONFLICT (usuario_id) DO UPDATE SET orgao_id = EXCLUDED.orgao_id;

            DO $$
            BEGIN
                ALTER TABLE app_usuarios ADD CONSTRAINT ck_app_usuarios_tipo
                    CHECK (tipo_usuario IN ('ACADEMICO', 'SUPERVISOR')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_usuarios ADD CONSTRAINT ck_app_usuarios_cpf
                    CHECK (length(regexp_replace(cpf, '\D', '', 'g')) = 11) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_academicos ADD CONSTRAINT ck_app_academicos_tipo_ensino
                    CHECK (tipo_ensino IN ('', 'Médio', 'Superior')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_academicos ADD CONSTRAINT ck_app_academicos_situacao
                    CHECK (situacao_academico IN ('Acadêmico ativo', 'Acadêmico desativado')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_pontos ADD CONSTRAINT ck_app_pontos_status
                    CHECK (status IN ('PENDENTE', 'PRESENTE', 'AUSENTE', 'FALTA_JUSTIFICADA', 'FALTA_NAO_JUSTIFICADA', 'PRESENCA_REGULARIZADA')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_historicos ADD CONSTRAINT ck_app_historicos_tipo_dia
                    CHECK (tipo_dia IN ('UTIL', 'SABADO', 'DOMINGO', 'FERIADO')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                ALTER TABLE app_ausencias DROP CONSTRAINT IF EXISTS ck_app_ausencias_tipo;
                ALTER TABLE app_ausencias ADD CONSTRAINT ck_app_ausencias_tipo
                    CHECK (tipo IN ('AUSENTE', 'JUSTIFICADA', 'NAO_JUSTIFICADA', 'REGULARIZADA')) NOT VALID;
            EXCEPTION WHEN duplicate_object THEN NULL;
            END $$;

            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM pg_indexes WHERE schemaname = 'public' AND indexname = 'ux_app_usuarios_email_lower'
                ) THEN
                    IF NOT EXISTS (
                        SELECT lower(email)
                        FROM app_usuarios
                        GROUP BY lower(email)
                        HAVING count(*) > 1
                    ) THEN
                        CREATE UNIQUE INDEX ux_app_usuarios_email_lower ON app_usuarios (lower(email));
                    ELSE
                        CREATE INDEX IF NOT EXISTS ix_app_usuarios_email_lower ON app_usuarios (lower(email));
                    END IF;
                END IF;
            END $$;
            CREATE INDEX IF NOT EXISTS ix_app_usuarios_tipo_usuario ON app_usuarios (tipo_usuario);
            CREATE INDEX IF NOT EXISTS ix_app_usuarios_orgao_id ON app_usuarios (orgao_id);
            CREATE INDEX IF NOT EXISTS ix_app_academicos_orgao_id ON app_academicos (orgao_id);
            CREATE INDEX IF NOT EXISTS ix_app_academicos_supervisor_id ON app_academicos (supervisor_id);
            CREATE INDEX IF NOT EXISTS ix_app_pontos_academico_data ON app_pontos (academico_id, data);
            CREATE INDEX IF NOT EXISTS ix_app_pontos_status ON app_pontos (status);
            CREATE INDEX IF NOT EXISTS ix_app_historicos_mes ON app_historicos (academico_id, ano, mes);
            CREATE INDEX IF NOT EXISTS ix_app_historicos_tipo_dia ON app_historicos (tipo_dia);
            CREATE INDEX IF NOT EXISTS ix_app_ausencias_academico_data ON app_ausencias (academico_id, data);
            CREATE INDEX IF NOT EXISTS ix_app_ausencias_supervisor_id ON app_ausencias (supervisor_id);

            CREATE OR REPLACE VIEW usuarios AS
            SELECT id, nome_completo, cpf, data_nascimento, email, tipo_usuario, orgao, orgao_id,
                   ativo, criado_em, atualizado_em, criado_por, atualizado_por
            FROM app_usuarios;

            CREATE OR REPLACE VIEW academicos AS
            SELECT a.*, u.nome_completo, u.cpf, u.data_nascimento, u.email, u.orgao
            FROM app_academicos a
            JOIN app_usuarios u ON u.id = a.usuario_id;

            CREATE OR REPLACE VIEW supervisores AS
            SELECT s.*, u.nome_completo, u.cpf, u.email, u.orgao
            FROM app_supervisores s
            JOIN app_usuarios u ON u.id = s.usuario_id;

            CREATE OR REPLACE VIEW pontos AS
            SELECT * FROM app_pontos;

            CREATE OR REPLACE VIEW historico_mensal AS
            SELECT * FROM app_historicos;

            CREATE OR REPLACE VIEW ausencias AS
            SELECT * FROM app_ausencias;

            CREATE OR REPLACE VIEW orgaos AS
            SELECT * FROM app_orgaos;

            CREATE OR REPLACE VIEW observacoes_supervisor AS
            SELECT id, academico_id, make_date(ano, mes, dia) AS data, observacao_supervisor,
                   atualizado_por_supervisor_id, atualizado_em
            FROM app_historicos
            WHERE observacao_supervisor <> '';
            """, con);

        await cmd.ExecuteNonQueryAsync();
    }

    public static async Task SincronizarVinculosInstitucionais(string connectionString)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            INSERT INTO app_supervisores (usuario_id, orgao_id)
            SELECT id, orgao_id
            FROM app_usuarios
            WHERE tipo_usuario = 'SUPERVISOR'
            ON CONFLICT (usuario_id) DO UPDATE SET orgao_id = EXCLUDED.orgao_id;

            UPDATE app_academicos a
            SET supervisor_id = s.usuario_id
            FROM app_supervisores s
            WHERE a.supervisor_id IS NULL
              AND a.orgao_id IS NOT NULL
              AND s.orgao_id = a.orgao_id;
            """, con);

        await cmd.ExecuteNonQueryAsync();
    }

    public static async Task<int> InserirUsuario(NpgsqlConnection con, NpgsqlTransaction tx, CadastroUsuarioRequest dados, string cpf, string tipo)
    {
        await using var cmd = new NpgsqlCommand("""
            WITH orgao_upsert AS (
                INSERT INTO app_orgaos (nome)
                VALUES (@orgao)
                ON CONFLICT (nome) DO UPDATE SET nome = EXCLUDED.nome
                RETURNING id
            )
            INSERT INTO app_usuarios (nome_completo, cpf, data_nascimento, email, senha_hash, tipo_usuario, orgao, orgao_id)
            VALUES (@nome, @cpf, @dataNascimento, @email, @senhaHash, @tipo, @orgao, (SELECT id FROM orgao_upsert))
            ON CONFLICT (cpf) DO NOTHING
            RETURNING id
            """, con, tx);

        cmd.Parameters.AddWithValue("nome", dados.NomeCompleto.Trim());
        cmd.Parameters.AddWithValue("cpf", cpf);
        cmd.Parameters.AddWithValue("dataNascimento", (object?)dados.DataNascimento ?? DBNull.Value);
        cmd.Parameters.AddWithValue("email", dados.Email.Trim());
        cmd.Parameters.AddWithValue("senhaHash", Texto.HashSenha(dados.Senha));
        cmd.Parameters.AddWithValue("tipo", tipo);
        cmd.Parameters.AddWithValue("orgao", dados.Orgao.Trim());

        var id = await cmd.ExecuteScalarAsync();
        if (id == null)
            throw new InvalidOperationException("Ja existe um cadastro com este CPF.");

        return Convert.ToInt32(id);
    }

    public static async Task<object?> BuscarUsuarioResposta(string connectionString, int id, bool comPontoHoje = false)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            SELECT u.*, a.*,
                   p.id AS ponto_id, p.data AS ponto_data, p.entrada AS ponto_entrada,
                   p.saida AS ponto_saida, p.horas_cumpridas AS ponto_horas_cumpridas,
                   p.status AS ponto_status
            FROM app_usuarios u
            LEFT JOIN app_academicos a ON a.usuario_id = u.id
            LEFT JOIN app_pontos p ON p.academico_id = u.id AND p.data = CURRENT_DATE
            WHERE u.id = @id
            """, con);

        cmd.Parameters.AddWithValue("id", id);

        await using var reader = await cmd.ExecuteReaderAsync();
        if (!await reader.ReadAsync())
            return null;

        return comPontoHoje && Valor.TemColuna(reader, "ponto_id")
            ? Resposta.AcademicoSupervisor(reader)
            : Resposta.Usuario(reader);
    }

    public static async Task<UsuarioInterno?> BuscarUsuarioInterno(string connectionString, int id)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            SELECT id, nome_completo, cpf, email, tipo_usuario, orgao, orgao_id
            FROM app_usuarios
            WHERE id = @id
            """, con);

        cmd.Parameters.AddWithValue("id", id);
        await using var reader = await cmd.ExecuteReaderAsync();

        return await reader.ReadAsync()
            ? new UsuarioInterno(
                reader.GetInt32(0),
                reader.GetString(1),
                reader.GetString(2),
                reader.GetString(3),
                reader.GetString(4),
                reader.GetString(5),
                reader.IsDBNull(6) ? null : reader.GetInt32(6))
            : null;
    }

    public static async Task<PontoInterno?> BuscarPontoRegistro(NpgsqlConnection con, int academicoId, DateTime data)
    {
        await using var cmd = new NpgsqlCommand("""
            SELECT id, data, entrada, saida, horas_cumpridas, status
            FROM app_pontos
            WHERE academico_id = @academicoId AND data = @data
            """, con);

        cmd.Parameters.AddWithValue("academicoId", academicoId);
        cmd.Parameters.AddWithValue("data", data.Date);

        await using var reader = await cmd.ExecuteReaderAsync();
        if (!await reader.ReadAsync())
            return null;

        return new PontoInterno(
            reader.GetInt32(0),
            reader.GetDateTime(1),
            reader.IsDBNull(2) ? null : reader.GetDateTime(2),
            reader.IsDBNull(3) ? null : reader.GetDateTime(3),
            reader.GetDouble(4),
            reader.GetString(5));
    }

    public static async Task<object?> BuscarPonto(string connectionString, int academicoId, DateTime data)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            SELECT id, data, entrada, saida, horas_cumpridas, status
            FROM app_pontos
            WHERE academico_id = @academicoId AND data = @data
            """, con);

        cmd.Parameters.AddWithValue("academicoId", academicoId);
        cmd.Parameters.AddWithValue("data", data.Date);

        await using var reader = await cmd.ExecuteReaderAsync();
        return await reader.ReadAsync() ? Resposta.Ponto(reader) : null;
    }

    public static async Task SincronizarHistorico(NpgsqlConnection con, int academicoId, DateTime data)
    {
        var feriado = Feriado(data);
        await using var cmd = new NpgsqlCommand("""
            INSERT INTO app_historicos (
                academico_id, ano, mes, dia, entrada, saida, observacao_supervisor,
                tipo_dia, descricao_feriado, atualizado_em
            )
            SELECT @academicoId, @ano, @mes, @dia, p.entrada, p.saida,
                   COALESCE(NULLIF(@descricaoFeriado, ''), ''),
                   @tipoDia, @descricaoFeriado, now()
            FROM app_pontos p
            WHERE p.academico_id = @academicoId AND p.data = @data
            ON CONFLICT (academico_id, ano, mes, dia) DO UPDATE
            SET entrada = EXCLUDED.entrada,
                saida = EXCLUDED.saida,
                tipo_dia = EXCLUDED.tipo_dia,
                descricao_feriado = EXCLUDED.descricao_feriado,
                atualizado_em = now()
            """, con);

        cmd.Parameters.AddWithValue("academicoId", academicoId);
        cmd.Parameters.AddWithValue("ano", data.Year);
        cmd.Parameters.AddWithValue("mes", data.Month);
        cmd.Parameters.AddWithValue("dia", data.Day);
        cmd.Parameters.AddWithValue("data", data.Date);
        cmd.Parameters.AddWithValue("tipoDia", feriado.TipoDia);
        cmd.Parameters.AddWithValue("descricaoFeriado", feriado.Descricao);
        await cmd.ExecuteNonQueryAsync();
    }

    public static async Task SalvarObservacao(NpgsqlConnection con, int academicoId, DateTime data, string observacao, int? supervisorId)
    {
        var feriado = Feriado(data);
        await using var cmd = new NpgsqlCommand("""
            INSERT INTO app_historicos (
                academico_id, ano, mes, dia, observacao_supervisor, tipo_dia,
                descricao_feriado, atualizado_por_supervisor_id, atualizado_em
            )
            VALUES (@academicoId, @ano, @mes, @dia, @observacao, @tipoDia, @descricaoFeriado, @supervisorId, now())
            ON CONFLICT (academico_id, ano, mes, dia) DO UPDATE
            SET observacao_supervisor = EXCLUDED.observacao_supervisor,
                atualizado_por_supervisor_id = EXCLUDED.atualizado_por_supervisor_id,
                atualizado_em = now()
            """, con);

        cmd.Parameters.AddWithValue("academicoId", academicoId);
        cmd.Parameters.AddWithValue("ano", data.Year);
        cmd.Parameters.AddWithValue("mes", data.Month);
        cmd.Parameters.AddWithValue("dia", data.Day);
        cmd.Parameters.AddWithValue("observacao", observacao);
        cmd.Parameters.AddWithValue("tipoDia", feriado.TipoDia);
        cmd.Parameters.AddWithValue("descricaoFeriado", feriado.Descricao);
        cmd.Parameters.AddWithValue("supervisorId", (object?)supervisorId ?? DBNull.Value);
        await cmd.ExecuteNonQueryAsync();
    }

    public static async Task<List<object>> HistoricoMensal(string connectionString, int academicoId, int ano, int mes)
    {
        await using var con = await Abrir(connectionString);
        await using var cmd = new NpgsqlCommand("""
            SELECT h.*, p.entrada AS ponto_entrada, p.saida AS ponto_saida,
                   p.horas_cumpridas, p.status AS ponto_status
            FROM app_historicos h
            LEFT JOIN app_pontos p ON p.academico_id = h.academico_id
                AND p.data = make_date(h.ano, h.mes, h.dia)
            WHERE h.academico_id = @academicoId AND h.ano = @ano AND h.mes = @mes
            """, con);

        cmd.Parameters.AddWithValue("academicoId", academicoId);
        cmd.Parameters.AddWithValue("ano", ano);
        cmd.Parameters.AddWithValue("mes", mes);

        var salvos = new Dictionary<int, object>();
        await using (var reader = await cmd.ExecuteReaderAsync())
        {
            while (await reader.ReadAsync())
                salvos[reader.GetInt32(reader.GetOrdinal("dia"))] = Resposta.Historico(reader);
        }

        var dias = new List<object>();
        for (var dia = 1; dia <= DateTime.DaysInMonth(ano, mes); dia++)
        {
            if (salvos.TryGetValue(dia, out var salvo))
            {
                dias.Add(salvo);
                continue;
            }

            var data = new DateTime(ano, mes, dia);
            var feriado = Feriado(data);
            dias.Add(new
            {
                id = 0,
                academicoId,
                ano,
                mes,
                dia,
                data,
                entrada = (DateTime?)null,
                saida = (DateTime?)null,
                horaEntrada = (DateTime?)null,
                horaSaida = (DateTime?)null,
                horasCumpridas = 0d,
                status = "AUSENTE",
                observacaoSupervisor = feriado.Descricao,
                tipoDia = feriado.TipoDia,
                descricaoFeriado = feriado.Descricao
            });
        }

        return dias;
    }

    public static (string TipoDia, string Descricao) Feriado(DateTime data)
    {
        var tipoDia = data.DayOfWeek switch
        {
            DayOfWeek.Saturday => "SABADO",
            DayOfWeek.Sunday => "DOMINGO",
            _ => "UTIL"
        };

        var feriados = new Dictionary<(int, int), string>
        {
            [(5, 1)] = "Dia do Trabalhador",
            [(6, 4)] = "Corpus Christi",
            [(9, 7)] = "Independencia do Brasil",
            [(10, 12)] = "Nossa Senhora Aparecida",
            [(11, 2)] = "Finados",
            [(11, 20)] = "Consciencia Negra",
            [(12, 25)] = "Natal"
        };

        return feriados.TryGetValue((data.Month, data.Day), out var descricao)
            ? ("FERIADO", descricao)
            : (tipoDia, string.Empty);
    }
}
